// Cloudinary URLs for carousel images
// These URLs are generated by running: node scripts/uploadCarouselToCloudinary.js
// in the backend server directory

export const CAROUSEL_IMAGES = [
  // Placeholder URLs - Run uploadCarouselToCloudinary.js script to get actual URLs
  // Then replace these with the Cloudinary URLs from the script output
  '/images/0.jpg',
  '/images/1.jpg',
  '/images/2.jpg',
  '/images/4.jpg',
  '/images/5.jpg'
];

// Note: After running the upload script, replace the above with actual Cloudinary URLs like:
// 'https://res.cloudinary.com/YOUR_CLOUD_NAME/image/upload/v1234567890/gym-website/carousel/0.jpg',
