// Cloudinary URLs for carousel images
// These URLs are generated by running: node scripts/uploadCarouselToCloudinary.js
// in the backend server directory

export const CAROUSEL_IMAGES = [
  "https://res.cloudinary.com/dtslb5uic/image/upload/v1762180708/gym-website/carousel/0.jpg",
  "https://res.cloudinary.com/dtslb5uic/image/upload/v1762180746/gym-website/carousel/1.jpg",
  "https://res.cloudinary.com/dtslb5uic/image/upload/v1762180776/gym-website/carousel/2.jpg",
  "https://res.cloudinary.com/dtslb5uic/image/upload/v1762180825/gym-website/carousel/4.jpg",
  "https://res.cloudinary.com/dtslb5uic/image/upload/v1762180877/gym-website/carousel/5.jpg",
];

// Note: After running the upload script, replace the above with actual Cloudinary URLs like:
// 'https://res.cloudinary.com/YOUR_CLOUD_NAME/image/upload/v1234567890/gym-website/carousel/0.jpg',
